version: '3.9'
services:
  metabase-ssl:
    image: metabase/metabase-enterprise:v1.46.0
    container_name: metabase-ssl
    hostname: metabase-ssl
    volumes: 
    - /dev/urandom:/dev/random:ro
    - $PWD/selfsigned.jks:/app/selfsigned.jks
    ports:
      - 3000:3000
      - 8443:8443
    environment:
      - "MB_JETTY_SSL=true"
      - "MB_JETTY_SSL_PORT=8443"
      - "MB_JETTY_SSL_KEYSTORE=/app/selfsigned.jks"
      - "MB_JETTY_SSL_KEYSTORE_PASSWORD=storepass"
      - "JAVA_OPTS=-XX:MaxRAMPercentage=90"
    cpus: 1
    mem_limit: 2048m
    networks: 
      - metanet1-ssl
  setup-ssl:
    image: bash:5.1.16
    container_name: setup-ssl
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1-ssl
    depends_on:
      - metabase-ssl
    command: sh /tmp/metabase-setup.sh metabase-ssl:3000
    cpus: 1
    mem_limit: 128m
networks: 
  metanet1-ssl:
    driver: bridge